stages:
  - build
  - test
  - release
  - preprod
  - integration
  - prod

build:
  stage: build
  script:
   - virtualenv env
   - source env/bin/activate
   - pip install -r requirements.txt
   - python manage.py check

test:
  stage: test
  script:
   - virtualenv env
   - source env/bin/activate
   - pip install -r requirements.txt
   - python manage.py test taskManager

dast-zap-base:
  stage: integration
  script:
   - zap-baseline.py -t https://prod-hynqkdiy.lab.practical-devsecops.training

dast-zap:
  stage: integration
  variables:
    website: "https://prod-xiqxodcj.lab.practical-devsecops.training/"
  script:
   - wget https://github.com/zaproxy/zaproxy/releases/download/v2.9.0/ZAP_2.9.0_Linux.tar.gz
   - tar -xzvf ZAP_2.9.0_Linux.tar.gz  
   - mv ZAP_2.9.0/ /zap/
   - rsync -av ZAP_2.9.0/ /zap/
  #  - wget https://github.com/zaproxy/zaproxy/releases/download/v2.9.0/ZAP_2_9_0_unix.sh
  #  - chmod +x ZAP_2_9_0_unix.sh
  #  - ./ZAP_2_9_0_unix.sh
  #  - echo 'deb http://download.opensuse.org/repositories/home:/cabelo/xUbuntu_18.04/ /' | sudo tee /etc/apt/sources.list.d/home:cabelo.list
  #  - curl -fsSL https://download.opensuse.org/repositories/home:cabelo/xUbuntu_18.04/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/home:cabelo.gpg > /dev/null
  #  - wget https://packages.chef.io/files/stable/inspec/4.18.114/ubuntu/16.04/inspec_4.18.114-1_amd64.deb

   - wget https://download.opensuse.org/repositories/home:/cabelo/xUbuntu_18.04/amd64/owasp-zap_2.9.0_amd64.deb
   - dpkg -i owasp-zap_2.9.0_amd64.deb
   - mkdir /zap/wrk
   - zap-baseline.py -t https://prod-dcomuldh.lab.practical-devsecops.training -J dast-zap-report.json
  allow_failure: true

zap-baseline: 
  stage: ​integration
  variables:
    website: "https://prod-xiqxodcj.lab.practical-devsecops.training/"
  script:
    -​ ​docker​ ​run​ ​-t​ ​--rm​ ​owasp/zap2docker-stable​ ​zap-baseline.py​ ​-t ${website}
    # - docker run -t owasp/zap2docker-stable zap-baseline.py -j -t https://10.0.1.22/
  after_script:
   # clean up the image to save the disk space
    - ​docker​ ​rmi​ ​owasp/zap2docker-stable 
  allow_failure: true